services:
  simulator:
    build: ./simulator
    container_name: api_simulator
    ports:
      - "9000:8000"

  db:
    image: postgres:16
    container_name: monitoring_db
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor -d monitoring"]
      interval: 5s
      timeout: 5s
      retries: 5

  monitor:
    build: .
    container_name: monitoring_platform
    depends_on:
      db:
        condition: service_healthy
      simulator:
        condition: service_started
    environment:
      SIMULATOR_URL: http://simulator:8000
      DATABASE_URL: postgresql://monitor:monitor@db:5432/monitoring
    ports:
      - "8000:8000"

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboard/grafana/provisioning:/etc/grafana/provisioning
      - ./dashboard/grafana/dashboards:/var/lib/grafana/dashboards
volumes:
  grafana_data:
  
