services:
  simulator:
    build: ./simulator
    container_name: api_simulator
    ports:
      - "9000:8000"

  db:
    image: postgres:16
    container_name: monitoring_db
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor -d monitoring"]
      interval: 5s
      timeout: 5s
      retries: 5

  monitor:
    build: .
    container_name: monitoring_platform
    depends_on:
      simulator:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      SIMULATOR_URL: http://simulator:8000
      DATABASE_URL: postgresql://monitor:monitor@db:5432/monitoring
    ports:
      - "8000:8000"
